# This file is generated by GitHub Actions. Do not edit manually.
# Generated from: https://github.com/hongkongkiwi/rusty-commit

$ErrorActionPreference = 'Stop'
$toolsPath = Split-Path -Parent $MyInvocation.MyCommand.Definition

$packageName = 'rusty-commit'
$installDir = "$env:ProgramFiles\$packageName"

# Remove the binary
if (Test-Path $installDir) {
    Remove-Item -Path $installDir -Recurse -Force
    Write-Host "$packageName has been uninstalled."
}

# Note: We don't remove from PATH here as that would require a system restart
# The orphaned PATH entry is harmless
