# This file is generated by GitHub Actions. Do not edit manually.
# Generated from: https://github.com/hongkongkiwi/rusty-commit
# Nix overlay for rusty-commit

{ lib, stdenv, fetchurl }:

stdenv.mkDerivation rec {
  pname = "rusty-commit";
  version = "__VERSION__";

  src = fetchurl {
    url = "https://github.com/hongkongkiwi/rusty-commit/releases/download/v${version}/rusty-commit-v${version}-x86_64-unknown-linux-musl.tar.gz";
    sha256 = "__SHA256_X86_64__";
  };

  nativeBuildInputs = [];

  installPhase = ''
    mkdir -p $out/bin
    cp rco $out/bin/rco
    chmod +x $out/bin/rco
  '';

  meta = with lib; {
    description = "AI-powered commit message generator written in Rust";
    longDescription = ''
      Rusty-commit (rco) is a modern, AI-powered git commit message generator that helps
      you create meaningful, standardized commit messages following Conventional Commits.
      Supports 100+ AI providers including OpenAI, Claude, Groq, Cerebras, and more.
    '';
    homepage = "https://github.com/hongkongkiwi/rusty-commit";
    license = licenses.mit;
    maintainers = [ maintainers.hongkongkiwi ];
    platforms = [ "x86_64-linux" "aarch64-linux" ];
  };
}
