name: CodeRabbit Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  coderabbit:
    name: CodeRabbit AI Review
    runs-on: ubuntu-latest
    steps:
      - name: CodeRabbit AI Review
        uses: coderabbitai/ai-pr-reviewer@latest
        with:
          # CodeRabbit will automatically use the configuration from .coderabbit.yaml
          # No additional configuration needed here
          debug: false